const turistas= [
    {
        foto: "img/danielita.jpg",
        id: "56451" ,
        Nombre: "Daniela",
        Edad: 26,
        genero: "femenino",
        procedencia: "colombian",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["castronomia","cultura"],
    },
    {
        foto: "img/andres.jpg",
        id: "23893" ,
        Nombre: "Andres",
        Edad: 30,
        genero: "masculino",
        procedencia: "colombian",
        idioma:["español","ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["nocturnos"],
    },
    {
        foto: "img/luisa.jpg",
        id: "63489" ,
        Nombre: "Luisa",
        Edad: 20,
        genero: "femenino",
        procedencia: "colombian",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["deporte","gastronomia"],
    },
    {
        foto: "img/angel.jpg",
        id: "19841981" ,
        Nombre: "Angel",
        Edad: 28,
        genero: "masculino",
        procedencia: "argentino",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["nocturnos","historia"],
    },
    {
        foto: "img/victor.jpg",
        id: "48151" ,
        Nombre: "Victor",
        Edad: 35,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["cultura","historia"],
    },
    {
        foto: "img/julian.jpg",
        id: "28465" ,
        Nombre: "Julian",
        Edad: 18,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["nocturnos","gastronomia"],
    },
    {
        foto: "img/tomas.jpg",
        id: "1841656" ,
        Nombre: "tomas",
        Edad: 18,
        genero: "masculino",
        procedencia: "americano",
        idioma:["español","ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["cultura","gastronomia"],
    },
    {
        foto: "img/cristian.jpg",
        id: "28465" ,
        Nombre: "Cristian",
        Edad: 32,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["nocturnos","museos"],
    },
    {
        foto: "img/felipe.jpg",
        id: "198465" ,
        Nombre: "Felipe",
        Edad: 22,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["cultura","historia"],
    },
    {
        foto: "img/manu.jpg",
        id: "1165165" ,
        Nombre: "Manuela",
        Edad: 22,
        genero: "femenino",
        procedencia: "americano",
        idioma:["ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        categoriasFav:["cultura","historia","gastronomia"],
    },

];





    